name: tmdb_dart
description: "A comprehensive Dart client library for The Movie Database (TMDB) API"
version: 0.1.0
homepage: https://github.com/example/tmdb_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^4.0.0
  json_annotation: ^4.8.1
  # Optional dependency for caching in Flutter apps
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  test: ^1.24.0
  mockito: ^5.4.4
  build_test: ^3.4.1
  lints: ^6.0.0
  http_mock_adapter: ^0.6.0
  fake_async: ^1.3.1
  coverage: ^1.7.0
